name: build Pipeline

on:
  workflow_dispatch:
    inputs:
      aviator_release_cut_id:
        description: "Database ID of release cut"
        required: false
        type: string
      aviator_release_cut_commit_hash:
        description: "Commit SHA, branch name, or tag of the HEAD to be built"
        required: false
        type: string
      aviator_release_candidate_version:
        description: "Name of the version"
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      # Need write access to contents to git-tag.
      contents: "write"
      id-token: "write"
    steps:
      - name: Print the inputs
        run: |
          echo "Inputs:"
          echo "aviator_release_cut_id=${{ inputs.aviator_release_cut_id }}"
          echo "aviator_release_cut_commit_hash=${{ inputs.aviator_release_cut_commit_hash }}"
          echo "aviator_release_candidate_version=${{ inputs.aviator_release_candidate_version }}"
